apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-hub-deployment
  labels:
    app: test-hub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-hub
  template:
    metadata:
      labels:
        app: test-hub
    spec:
      containers:
        - name: test-hub
          image: shailendrajr/test_hub:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
