apiVersion: v1
kind: Service
metadata:
  name: test-hub-service
  labels:
    app: test-hub
spec:
  type: LoadBalancer
  selector:
    app: test-hub
  ports:
    - name: http
      port: 80
      targetPort: 80
